[package]
name = "AuthentiChain"
version = "1.0.0"

[addresses]
# Main address (the one you generated)
AuthentiChain = "0x8d8862e603400092902b037caec23790f8d3c0b33e37e30efb5025984826dfb1"

[dev-addresses]
# Dev address (same as the main address for Devnet)
AuthentiChain = "0x8d8862e603400092902b037caec23790f8d3c0b33e37e30efb5025984826dfb1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
